# Generated by Django 5.1.2 on 2024-11-05 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersuggestion',
            name='flavor_suggestion',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergy_warning',
        ),
        migrations.RemoveField(
            model_name='seasonalflavor',
            name='availability_date',
        ),
        migrations.AddField(
            model_name='customersuggestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customersuggestion',
            name='flavor',
            field=models.CharField(default='non', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasonalflavor',
            name='available_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='seasonalflavor',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Winter', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seasonalflavor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
