# Generated by Django 4.2.16 on 2024-11-05 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_customersuggestion_flavor_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersuggestion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customersuggestion',
            name='flavor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
